# Generated by Django 2.2 on 2020-01-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='收货人')),
                ('phone', models.CharField(max_length=128, verbose_name='收货人电话')),
                ('receiving', models.IntegerField(choices=[(0, '收货时间不限'), (1, '周六日/节假日收货'), (2, '周一到周五收货')], verbose_name='收货时间')),
                ('address', models.CharField(max_length=255, verbose_name='收货详细地址')),
            ],
            options={
                'verbose_name': '地址信息',
                'verbose_name_plural': '地址管理',
            },
        ),
    ]
