# Generated by Django 2.2 on 2020-01-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('tel', models.CharField(max_length=11, verbose_name='电话')),
                ('detail', models.TextField(blank=True, help_text='描述用户特征', null=True, verbose_name='用户描述')),
                ('sex', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], verbose_name='性别')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户管理',
            },
        ),
    ]
