# Generated by Django 2.2 on 2020-01-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inxapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
    ]
